.jobs_tags: &jtags
  tags:
    - cli
.only-default: &only-default
  only:
    - merge_request
    - master
.only-release: &only-release
  only:
    - master

image: hello-world

stages:
  -build
  -spec
  -staging
  -deploy

make:
  stage: build
  script:
    - echo "[TODO] MAKE JOB"
    - exit 1
  <<: *jtags
  <<: *only-default  

test:
  stage: spec
  script:
    - echo "[TODO] TEST JOB"
    - exit 1
  <<: *jtags
  <<: *only-default

pack:
  stage: staging
  script:
    - echo "[TODO] PACK JOB"
    - exit 1
  <<: *jtags
  <<: *only-release

publish:
  stage: deploy
  script:
    - echo "[TODO] PUBLISH JOB"
    - exit 1
  <<: *jtags
  <<: *only-release